MAJORS = {
    "computer_engineering": ["computer science", "software engineering", "engineering", "information systems", "data science",
                             "computer science and engineering", "computer engineering", "electronics engineering",
                             "engineering tech", "industrial engineering", "mechanical engineering",
                             "computer and information science", "computer", "software development",
                             "computer systems", "computer information systems", "computer systems engineering",
                             "computer science and electrical engineering", "general engineering",
                             "computer and information systems", "computer science and mathematics", "computer programming",
                             "cybersecurity", "community development"],
    "engineering": ["environmental engineering", "chemical engineering", "civil engineering", "bioengineering",
                    "biological engineering", "biomedical engineering", "aerospace engineering",
                    "mechatronics engineering"],
    "electronics": ["electronics", "electrical engineering", "electrical engineering and computer science", "robotics"],
    "music": ["music"],
    "business_and_management": ["business", "marketing", "business marketing", "project management",
                                "organizational leadership", "ministry", "management", "general business",
                                "business administration and management", "product marketing", "business management",
                                "management studies", "international business", "business administration",
                                "organizational management", "supply chain management",
                                "information systems management",  "operations management", "business admin"],
    "art": ["visual communications", "art", "film", "liberal arts", "photography", "studio arts", "art history",
            "studio art", "painting", "fine arts", "writing", "visual art", "design", "graphic design",
            "film and television", "television", "fashion design", "fine art", "digital art", "illustration",
            "theatre", "culinary arts", "creative writing"],
    "general_education": ["general education", "general studies"],
    "dental_hygiene": ["dental hygiene"],
    "economics": ["economics", "finance", "applied economics"],
    "science": ["information science", "biology", "chemistry", "mathematics", "physics", "statistics",
                "applied mathematics", "logic", "microbiology", "physical science", "general science",
                "exercise science", "molecular biology", "marine biology", "social sciences", "applied physics"],
    "geography": ["geography"],
    "communications": ["communications"],
    "qualifying": ["qualifying", "literature", "philosophy", "psychology", "history", "sociology", "french literature",
                   "asian american studies", "poetry", "comparative literature"],
    "languages": ["english language", "japanese studies", "english", "spanish", "english language and literature",
                  "chinese", "german language and culture", "german language", "english literature", "mandarin",
                  "spanish language", "french", "italian language", "italian", "german", "russian studies",
                  "french language studies", "chinese language", "french language", "chinese language and literature",
                  ],
    "medicine": ["medicine"],
    "tech_design": ["game design", "animation", "product design", "computer graphics", "computer application",
                    "web development", "industrial design"],
    "media": ["interactive media", "media management", "media studies", "advertising", "multimedia"],
    "human resources": ["human resources", "human resource management"],
    "finance": ["corporate finance", "international finance", "accounting", "business economics", "accountancy",
                "financial engineering"],
    "law": ["law", "pre law"],
    "health": ["global health", "public health", "health promotion", "health science"],
    "human services": ["consulting"]
    }

# MAJOR = {"counseling": 1, "international relations": 3, "astrophysics": 1, "astronomy": 2, "energy": 4,
#           "political science": 6,   "entrepreneurship": 24,
#          "labor relations": 1, "education": 19,
#
#            "neuroscience": 2,  "bioinformatics": 3,
#          "applied science": 3,   "politics": 2,
#           "broadcasting": 1, "communication": 25, "telecommunications": 12, "anthropology": 7,
#          "materials science": 1,
#           "teaching": 3,   "mining": 3,
#             "applied statistics": 1,  "management science": 8,
#          "commerce": 1,   "public relations": 2,
#            "serbian": 1,
#          "informatics": 7,
#          "cognitive science": 1,  "piano performance": 1,  "real estate": 1,
#            "journalism": 3,  "liberal studies": 2,
#          "leadership": 9, "physiology": 2,  "geophysics": 1,  "humanities": 3,
#             "oceanography": 1, "religious studies": 1,
#            "linguistics": 1, "counseling psychology": 1, "global studies": 2,
#          "architecture": 2, "entrepreneurial studies": 3,  "rhetoric": 3, "communication studies": 3, "
#
#             "public policy": 4,   "paralegal": 2, "kinesiology": 2,
#            "criminal justice": 3,
#            "interdisciplinary studies": 1, "drama": 1,  "pharmacology": 2,
#          "biomedical science": 2, "forensics": 1,   "international affairs": 1,
#             "homeland security": 1,
#          "broadcast journalism": 1,  "logistics": 1,
#            "actuarial science": 1,
#           "classics": 1}
